services:
  frontend:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html/
    depends_on:
      - php
      - mysql

  php:
    image: php:8-fpm-alpine3.17
    volumes:
      - ./src:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./src/logs:/var/www/logs
    env_file:
      - ./docker/vars.env

  composer:
    image: composer:latest
    volumes:
      - ./src:/app

  mysql:
    image: mariadb:10
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    env_file:
      - ./docker/vars.env
    networks:
      - sgnlnet

  adminer:
    image: adminer
    ports:
      - 8085:8080
    networks:
      - sgnlnet
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    depends_on:
      - mysql

volumes:
  dbdata:

networks:
  sgnlnet:
